### PR TITLE
Add bindings for loongarch64-linux-gnu

### PR DESCRIPTION
**Pull request by heiher**
Add bindings for [loongarch64-linux-gnu](https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html) (A tier-2 with host tools target).

### CODE REVIEW

**Comment by heiher** [comment]
Sorry, I ignored the action results.

**Review by ionut-arm — APPROVED** [review]
Apologies for the delay on our part - I wanted to ask if it'd be possible for you to update this with bindings from bindgen v0.66. Otherwise I'm happy with the PR.

**Comment by heiher** [comment]
> Apologies for the delay on our part - I wanted to ask if it'd be possible for you to update this with bindings from bindgen v0.66. Otherwise I'm happy with the PR.

Thanks for your review. This is done.

**Review by hug-dev — APPROVED** [review]

**Review by ionut-arm — APPROVED** [review]
👍🏻

**Pull request merged**
