### PR TITLE
Adjust code to compile under rust 1.80

### PR DESCRIPTION
**Pull request by keldonin**
fix for issue #216

### CODE REVIEW

**Comment by keldonin** [comment]
CI scripts fail, but for another reason this time. Can the project maintainer check out what's going on? The errors are about sections that have not been changed by this PR (indentation on comments)

**Comment by keldonin** [comment]
It seems like #217 and #218 are both needed together to go address this problem. I therefore combined changes from #218 into this PR, as #217 won't work alone, for the reasons #218 was created.
Hopefully this should make its way through the CI this time.

**Review by gowthamsk-arm — APPROVED** [review]
LGTM

**Review by ionut-arm — APPROVED** [review]
Thanks!

**Pull request merged**
