### PR TITLE
Use psa-crypto with updated zeroize

### PR DESCRIPTION
**Pull request by gowthamsk-arm**
Relates to #602

Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>

### CODE REVIEW

**Comment by ionut-arm** [comment]
The version of `cryptoki` we use in the Parsec service isn't the one from `main`, it's based on the [cryptoki-0.2.x](https://github.com/parallaxsecond/rust-cryptoki/tree/cryptoki-0.2.x) branch.

One thing to remember here is that if the version we'll be releasing of `psa-crypto` is going to be a "point" release (as in, we only increase the patch number), then that release can be included in the service (for example) without having to update the `Cargo.toml`, by just doing a `cargo update`.

Another thing to consider for the future is that `cryptoki` should really not depend on `psa-crypto`. We should implement those conversions somewhere else, preferably in the Parsec service. I think we only did it because you can't have `TryFrom` and `From` implemented outside the crate, but we could just use some functions to convert, like we do for everything else in the service.

**Comment by gowthamsk-arm** [comment]
Thanks for the comment Ionut. :) So in that case should we update the documentation to explicitly run `cargo update` before building the service and drop this PR along with the PR raised for the interfaces repo? 

Also regarding the `TryFrom` and `From` dependency, should I create an issue? :)

**Comment by ionut-arm** [comment]
> Thanks for the comment Ionut. :) So in that case should we update the documentation to explicitly run `cargo update` before building the service and drop this PR along with the PR raised for the interfaces repo?

We should update the documentation, but you will sometimes need a minor/major version update in the dependency, in which case you do need to change the `Cargo.toml` and release the other stuff as well.

> Also regarding the `TryFrom` and `From` dependency, should I create an issue? :)

Yes, please!

**Comment by wiktor-k** [comment]
:thinking: It would be nice to have a proper release of psa-crypto beforehand and then update to numbered version instead of somewhat ugly git dependency... Is there anything blocking psa-crypto from a new release?

(I've read https://github.com/parallaxsecond/parsec/issues/602 but releasing new psa-crypto doesn't seem to be a problem).

**Comment by gowthamsk-arm** [comment]
We will be releasing psa-crypto crate today. This MR will be dropped. :)

**Comment by gowthamsk-arm** [comment]
@ionut-arm I am creating the ticket for removing the conversions `impl TryFrom<psa_crypto::types::algorithm::Algorithm> for Mechanism` and `pub fn from_psa_crypto_hash` from this crate and implementing the conversion functions under Parsec. Is there anything else that should be considered as part of this ticket?

**Comment by ionut-arm** [comment]
> @ionut-arm I am creating the issue for removing the conversions `impl TryFrom<psa_crypto::types::algorithm::Algorithm> for Mechanism` and `pub fn from_psa_crypto_hash` from this crate and implementing the conversion functions under Parsec. Is there anything else that should be considered as part of this issue?

Nah, that should be enough - getting anything PSA-related removed from this crate is the goal

**Comment by gowthamsk-arm** [comment]
Created #100

**Comment by gowthamsk-arm** [comment]
Not required.

**Pull request closed without merging**
