### PR TITLE
Add script for regenerating bindings

### PR DESCRIPTION
**Pull request by ionut-arm**
This builds on #82 which did the same thing for the `0.2.x` version of the crates.

### CODE REVIEW

**Review by hug-dev — APPROVED** [review]
Pretty cool!! Will make so easy to add new bindings

**Comment by ionut-arm** [comment]
> I do miss the LF at the end of `regenerate_bindings.sh` but it's a minor thing

Fixed!

> Will make so easy to add new bindings

I need to have a look at adding the same for the other FFI crates.

**Comment by wiktor-k** [comment]
Btw I ran the script through [shellcheck](https://github.com/koalaman/shellcheck) and got the following:

```

In /tmp/x.sh line 15:
        rustup target install $target
                              ^-----^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
        rustup target install "$target"


In /tmp/x.sh line 19:
    cargo build --target $target --features generate-bindings
                         ^-----^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
    cargo build --target "$target" --features generate-bindings


In /tmp/x.sh line 20:
    find ../target/$target/ -name pkcs11_bindings.rs | xargs -I '{}' cp '{}' src/bindings/$target.rs
    ^-- SC2038 (warning): Use -print0/-0 or -exec + to allow for non-alphanumeric filenames.
                   ^-----^ SC2086 (info): Double quote to prevent globbing and word splitting.
                                                                                          ^-----^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
    find ../target/"$target"/ -name pkcs11_bindings.rs | xargs -I '{}' cp '{}' src/bindings/"$target".rs


In /tmp/x.sh line 23:
        rustup target remove $target
                             ^-----^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
        rustup target remove "$target"
```

I'm not a shell expert by any means so you'd have to decide if these lints are something to listen to but I wanted to provide yet another angle :)

**Comment by ionut-arm** [comment]
Ok, fixed those problems flagged by shellcheck.

**Pull request merged**
