### PR TITLE
Merge main into devel

### PR DESCRIPTION
**Pull request by mjb3279**
Merging `main` into `devel` to keep `devel` up-to-date

### CODE REVIEW

**Comment by hug-dev** [comment]
You can try but I think now (with your `Write` role), you should be able to rebase `devel` on top of `main` and force-push `devel` in the repo. If that does not work I can do it myself too. That's just to avoid the merge commit and keep the history linear but if we don't care that much we can just merge this.

**Comment by mjb3279** [comment]
I guess it's up to you.  The rebase will be annoying, replaying each of the commits in `devel` onto `main`.  At some point `devel` will merge back into `main`.

I tend to prefer merges, but again, up to you :)

**Comment by hug-dev** [comment]
I just rebased `devel` on top of `main` and force-pushed the branch. It's currently passing CI [now](https://github.com/parallaxsecond/rust-cryptoki/runs/3688721488), hope it will pass.

I figured it will be easier when we decide to lift the code-freeze because we will just be able to fast-forward the `main` branch with `devel` and delete `devel`.

**Comment by mjb3279** [comment]
So the problem with rebasing is that you lose all the merge history in `devel`.  Not sure if it matters.

**Comment by hug-dev** [comment]
Yeah not sure, as long as you don't lose commit history I'd say it's ok

**Pull request closed without merging**
