### PR TITLE
Fix SIGSEGV upon pkcs11.open_session_no_callbac

### PR DESCRIPTION
**Pull request by hansonchar**
https://github.com/parallaxsecond/rust-cryptoki/issues/72

Signed-off-by: Hanson Char <hanson.char@gmail.com>

### CODE REVIEW

**Comment by hug-dev** [comment]
Hey @hansonchar!!

Thanks for the detailed bug report and the PR. As this file is automatically generated from `bindgen`, I guess that a long term solution would be to fix the code-generation side directly, so that it's fixed for everyone? I am afraid that we will overwrite your fix if we re-generate the code.

Is there any issue about that on the `bindgen` repo? Might be worth to discuss with them too. Also @joechrisellis added the `libloading` feature in `bindgen` so he might be able to give pointers!

**Comment by hug-dev** [comment]
I'll let the others share their thoughts though! Maybe it does not hurt to include that temporary as long as the new bindings also contain it!

**Comment by ionut-arm** [comment]
As per my message in the issue - an approach that could help in the future with other problems as well could be to place those `libloading` calls from this PR in a separate method implemented in [`lib.rs`](https://github.com/parallaxsecond/rust-cryptoki/blob/main/cryptoki-sys/src/lib.rs), but allowing the user to decide which flags they want to pass down. Thoughts?

**Comment by hansonchar** [comment]
Great idea.

**Pull request closed without merging**
