### PR TITLE
Prepare release of changes to bindings

### PR DESCRIPTION
**Pull request by ionut-arm**
cc @ximon18

### CODE REVIEW

**Comment by ionut-arm** [comment]
Not sure if I'll be able to release this today, but will get to it tomorrow if not :)

**Review by wiktor-k — APPROVED** [review]
LGTM :tada:

**Comment by ximon18** [comment]
Thanks @ionut-arm!

I assume this will be a release of both cryptoki-sys and cryptoki, is that right?

Tomorrow or soon is fine, I just wanted to understand whether it would be soon or later, very welcome news, thankyou!

**Comment by ionut-arm** [comment]
> I assume this will be a release of both cryptoki-sys and cryptoki, is that right?

That's actually not necessary - because I'm bumping the patch number, you can simply do a `cargo update -p cryptoki-sys` and you'll be able to use the new version without an update to `cryptoki`.

**Comment by ximon18** [comment]
Don't you also need to update CHANGELOG.md?

**Comment by ximon18** [comment]
Hi all,

Do you plan to go ahead with the 0.1.4 release of `cryptoki-sys` soon? I ask because we're getting ready to make a new release candidate of our product and ideally would like to include this change but cannot as it is not released yet.

Ximon

**Comment by ionut-arm** [comment]
I was hoping to get another approval, but it should be fine as is. I'll release it now.

**Comment by ionut-arm** [comment]
Done!

**Comment by ximon18** [comment]
Thanks @ionut-arm !

**Pull request merged**
