### PR TITLE
Add SHA256-HMAC mechanism

### PR DESCRIPTION
**Pull request by jippeholwerda**
This PR adds the SHA256-HMAC mechanism. This has been tested on SoftHSM2 as well as the Utimaco HSM simulator.

### CODE REVIEW

**Review by wiktor-k — DISMISSED** [review]
This looks very straightforward. Thanks!

**Review by ionut-arm — APPROVED** [review]
Thanks for the patch!

**Review by wiktor-k — APPROVED** [review]

**Review by gowthamsk-arm — APPROVED** [review]
LGTM. Thanks.

**Comment by gowthamsk-arm** [comment]
Can you please rebase and resolve conflicts?:)

**Pull request merged**
