### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by ionut-arm**
Preparing to release new versions of the `cryptoki` crates.

(The version number of `cryptoki` had already been changed.)

cc @vkkoskie @ximon18

### CODE REVIEW

**Review by anta5010 — APPROVED** [review]

**Review by wiktor-k — APPROVED** [review]
Yep, looks good! 🚀

**Comment by hug-dev** [comment]
Looks good to me! Would be nice if @vkkoskie can give their green light, since they did so many changes and plans for the crate recently

**Comment by ionut-arm** [comment]
> My apologies for being silent so long. I was trying to take "holiday" as seriously as possible and took a break from hobby coding for a while. I have no objections.
> 
> Is the plan to publish immediately, or merge #68 first? I'll be responding there next.

Happy to see you back! :D 

There is no plan - I think it mostly depends on whether you have some personal projects that depend on #68 being in the next release. Otherwise I'd lean towards releasing as-is, since @ximon18 (who requested the release) has already updated some of his crates to work with the tip of `main`, and I think #68 would mean a lot more changes to deal with :)

**Comment by ionut-arm** [comment]
Okay, I've published `0.3.0` of `cryptoki` and `0.1.3` of `cryptoki-sys`.

@vkkoskie - if you'd like #68 into a release ASAP I'm happy to do a `0.4.0` of `cryptoki` right after the merge.

**Comment by vkkoskie** [comment]
No rush. I was thinking that having one breaking publication would be better than two from the perspective of having to update client code, but that's clearly not the case here.

**Comment by ionut-arm** [comment]
> @ionut-arm Uh, oh. 😉 It looks like you had 0.4.0 on the mind when you updated the Changelog file for 0.3.0.

oops 😅 Will fix in a future PR! Thanks for noticing!!

**Pull request merged**
