### PR TITLE
Add bindings for FreeBSD on x86-64.

### PR DESCRIPTION
**Pull request by ximon18**
This PR adds support for bindings for the FreeBSD on x86-64 target.

### CODE REVIEW

**Comment by ximon18** [comment]
I wonder if the CI failures are due to existing warnings now being treated by newer Rust as errors, and not due to my changes...?

**Review by hug-dev — APPROVED** [review]
Thanks a lot for the changes!! For some reason the DCO checks work now :+1:

**Comment by ximon18** [comment]
I wasn't familiar with the DCO checks and didn't notice they were failing. It took several attempts but I was finally able to edit and force push the commits until the DCO checks passed.

**Comment by ximon18** [comment]
Looking back at the last successful run of the "Execute CI script" step of the "Continuous Integration" job I see that [it used Rust 1.60.0](RUST_BACKTRACE=1 cargo test).

If I run `./ci.sh` locally with Rust 1.60.0 then the `cargo build` steps succeed, while with latest Rust 1.62.1 it fails as it does in GH Actions for this PR.

So indeed I think something is broken Cryptoki with latest Rust that has nothing to do with my PR.

**Comment by ximon18** [comment]
FYI I have run the commands in `ci.sh` on a FreeBSD 13.1 AWS EC2 VM (after having first installed Rust 1.60.0, the same toolchains as installed by `ci.yml`, and SoftHSM2 configured the same as by `ci.yml`) and all cargo build, fmt, clippy, and test commands succeed.

Details of the system used:
```
ec2-user@freebsd:~/rust-cryptoki-add-freebsd-bindings/cryptoki-sys $ uname -a
FreeBSD freebsd 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64
ec2-user@freebsd:~/rust-cryptoki-add-freebsd-bindings/cryptoki-sys $ rustup show
Default host: x86_64-unknown-freebsd
rustup home:  /home/ec2-user/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-freebsd
1.60.0-x86_64-unknown-freebsd (default)

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-unknown-linux-gnu
arm-unknown-linux-gnueabi
armv7-unknown-linux-gnueabi
armv7-unknown-linux-gnueabihf
i686-unknown-linux-gnu
powerpc64-unknown-linux-gnu
powerpc64le-unknown-linux-gnu
x86_64-apple-darwin
x86_64-pc-windows-msvc
x86_64-unknown-freebsd

active toolchain
----------------

1.60.0-x86_64-unknown-freebsd (default)
rustc 1.60.0 (7737e0b5c 2022-04-04)

ec2-user@freebsd:~/rust-cryptoki-add-freebsd-bindings/cryptoki-sys $ rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

Output of the `cargo test` step:

```
ec2-user@freebsd:~/rust-cryptoki-add-freebsd-bindings/cryptoki-sys $ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running unittests (/usr/home/ec2-user/rust-cryptoki-add-freebsd-bindings/target/debug/deps/cryptoki_sys-3cfb3ae00b600e7d)

running 22 tests
test bindgen_test_layout_CK_OTP_SIGNATURE_INFO ... ok
test bindgen_test_layout_CK_OTP_PARAMS ... ok
test bindgen_test_layout_CK_OTP_PARAM ... ok
test bindgen_test_layout__CK_ATTRIBUTE ... ok
test bindgen_test_layout__CK_C_INITIALIZE_ARGS ... ok
test bindgen_test_layout__CK_FUNCTION_LIST ... ok
test bindgen_test_layout__CK_DATE ... ok
test bindgen_test_layout__CK_INFO ... ok
test bindgen_test_layout__CK_MECHANISM ... ok
test bindgen_test_layout__CK_MECHANISM_INFO ... ok
test bindgen_test_layout__CK_SESSION_INFO ... ok
test bindgen_test_layout__CK_SLOT_INFO ... ok
test bindgen_test_layout__CK_TOKEN_INFO ... ok
test bindgen_test_layout__CK_VERSION ... ok
test bindgen_test_layout_ck_aes_cbc_encrypt_data_params ... ok
test bindgen_test_layout_ck_aes_ctr_params ... ok
test bindgen_test_layout_ck_des_cbc_encrypt_data_params ... ok
test bindgen_test_layout_ck_ecdh1_derive_params ... ok
test bindgen_test_layout_ck_key_derivation_string_data ... ok
test bindgen_test_layout_ck_gcm_params ... ok
test bindgen_test_layout_ck_rsa_pkcs_oaep_params ... ok
test bindgen_test_layout_ck_rsa_pkcs_pss_params ... ok

test result: ok. 22 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests cryptoki-sys

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by ximon18** [comment]
FYI I built my application on FreeBSD 13.1 using `--features cryptoki/generate-bindings` with the latest release of Cryptoki and was able to demonstrate that it works correctly with SoftHSM2 (i.e. can create keys, sign with them, query the token, etc) so the bindings seem to work in a real world context as well as with the tests in this repo.

**Comment by hug-dev** [comment]
Ah good find! I should have fixed the CI in #95 , you should be able to rebase once it's merged :ok_hand:

**Review by wiktor-k — APPROVED** [review]
I'm OK with this change with two notes:

1. Better to rebase when #95 is merged just to be on the safe-side.
2. The CI script needs some love and IMO should be rewritten to use GitHub's matrix builds because of visibility (I'm not saying it should be done now, just that it'd be a good idea).

**Comment by ximon18** [comment]
> The CI script needs some love and IMO should be rewritten to use GitHub's matrix builds because of visibility (I'm not saying it should be done now, just that it'd be a good idea).

Indeed, I had to count occurrences of "Finished" to try and work out which of the `cargo build` invocations was failing...

**Comment by ximon18** [comment]
@hug-dev @wiktor-k @ionut-arm: I'm not sure how the release planning for this project is done, do you know when a release might be made?

I'm asking because we're in the process of making a v0.10.0 release for the [Krill](https://github.com/NLnetLabs/krill) project, currently at rc2 stage, and this is the first release that enables our cryptoki powered PCKS#11 support by default.

While testing this release the lack of support (with standard build instructions) on FreeBSD was discovered. So I'm curious to know if we can expect to be able to make a third release candidate which fixes this issue, or should expect to wait longer and thus instead provide guidance to FreeBSD users/packagers of the final v0.10.0 release of Krill to disable the HSM feature or to build using '--features cryptoki/generate-bindings' when compiling.

Thanks,

Ximon

**Comment by wiktor-k** [comment]
I don't think there are any blockers for a new release and it's good that you're asking about it.

I'll ping @ionut-arm about that on Slack (still, I think he got the GitHub notification :) ).

**Pull request merged**
